### ISSUE TITLE
The aim of this mod

### ISSUE THREAD

**Issue by Ezhh** [Cat5TV/tps_technic#1]
Hi Robbie,

I know you are hoping I can help with this one, so could you please explain exactly how you want it to work? Should corium be locked to the spill priv like water/lava and made harmless, or removed completely? 

Also can you confirm if you are remembering to set enable_corium_griefing = false in minetest.conf?

**Comment by Cat5TV** [comment]
Thanks Ezhh. The initial goal (as in, first things first) is to remove these dangerous features on the TPS servers that use Technic, without having to manually modify the Technic core mod. Down the road, if we find there are good players who need HV / nuclear features, we can assess the importance of each and decide if we want to make more of a privilege-based system. For now though, removing the features altogether means removing the ability for them to be used in grief attacks, and that's the priority.

Yes, our confs have enable_corium_griefing = false, however that does not always seem sufficient (players seem to find a way around it, especially on Creative servers).

Cheers!
